### PR TITLE
Merge pull request #3 from cs2103-ay1819s2-w15-1/master

### PR DESCRIPTION
**Pull request by PhilipPhil**
Merge pull request #51 from PhilipPhil/master

### CODE REVIEW

**Comment by stanleymok** [comment]
compilation test failed

> Task :compileTestJava
/home/travis/build/CS2103-AY1819S2-W15-1/main/src/test/java/seedu/address/logic/commands/CommandTestUtil.java:8: error: cannot find symbol
import static seedu.address.logic.parser.CliSyntax.PREFIX_ADDRESS;
^

fix prefix_tag and prefix_address they're missing.

**Comment by ReinSheer** [comment]
There are some checkstyle errors. Fix that and we are good to go! Great job, and keep up the effort!

**Comment by PhilipPhil** [comment]
comments

**Comment by stanleymok** [comment]
update checkstyle errors as we go before wednesday

**Pull request merged**
