### PR TITLE
[W15-1] Fashion Match

### PR DESCRIPTION
**Pull request by PhilipPhil**
[W15-1] Fashion Match

### CODE REVIEW

**Comment by PhilipPhil** [comment]
why is this failing!

**Comment by rafflesandrison** [comment]
Please fix the check-style error.

**Comment by PhilipPhil** [comment]
how do I know what to fix with the  check-style error?

**Comment by leeyh20** [comment]
Run the checkstyle tests locally on IntelliJ using gradle commands.

**Comment by rafflesandrison** [comment]
Check out the details in travis. 
All the errors info are there.

You should be able to find the error messages somewhere at the middle portion.

It will tell you which line violates the checkstyle.

**Pull request closed without merging**
